apiVersion: v1
kind: Service
metadata:
  name: homarr
  namespace: homarr
spec:
  selector:
    app: homarr
    # app.kubernetes.io/name: homarr
    # app.kubernetes.io/instance: homarr
  ports:
    - name: http
      port: 7575
      targetPort: 7575
      protocol: TCP
  type: ClusterIP