apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
#     securityContext:
#       fsGroup: 33 # www-data group ID
#       runAsUser: 33 # www-data user ID
#       runAsGroup: 33 # www-data group ID

      containers:
        - name: audiobookshelf
          image: advplyr/audiobookshelf:2.32.1

#         securityContext:
#           allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap

          ports:
            - containerPort: 3005
              protocol: TCP

      restartPolicy: Always

#         volumeMounts:
#           - name: audiobookshelf-data
#             mountPath: /etc/audiobookshelf/data
#     volumes:
#       - name: audiobookshelf-data
#         persistentVolumeClaim:
#           claimName: audiobookshelf-data-pvc
