apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:+cJoW2E=,iv:UeTEdZmKjC/Q0FisKCurtoQbru+3K5VHeNx6tzhahc8=,tag:MbP3DCQOQS3ERvWJelEizQ==,type:str]
    admin-password: ENC[AES256_GCM,data:YzN7g4bDhEhi,iv:LXmYRTbeKjA48iCQkzJgcMwLX+7W+aRxJQlDYhEeoOA=,tag:GZDHaSwBmzGzOLy2H4qSvg==,type:str]
sops:
    age:
        - recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K2M4WXkwcmlXcXF5VDJx
            Wk5taC94a2xUL0ZtekpSUlA2eTlTNUF1LzNrClVycHJ5aWg0WkhjbTVUclFZam5m
            NWVDSEZrR0I0cFlhOWoyb0p0R2dGWUkKLS0tIHpweTRKQWd1UitjRGVYNmcyb3U1
            WjNYa2xzY2xvV2c2RTQ1dUdENXoyMmcKcbyG8Coz1OtbeAwlCj3jkHt+BPIG0JbC
            G7Xq6QQI5CJGOCYoIiH28pC62GOq9/KmTcLrp3h5zooHma22v1Q4Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T17:35:23Z"
    mac: ENC[AES256_GCM,data:uV6OJFlOeNQU0x+5Cm8rzAy1cZPUP5xf4kW3qgUdgWKOXTjkqTH4sJUgFXbvPHGEV8S0zMK9NxSklRZTnBveiweLPrdGWSe+DyGB3V/5k152kiAyed8HKEvG8N/2ZlreGHud1o7WHsPf0loTBh3N4D05ux1Eirt/Y0sUVDfSbPU=,iv:9T6MBpHlgVXi3SwG8OC1NaEuCHg029nTIh9zgQ/ZQPM=,tag:FbUNJaz+lKD2DpyVxgL3Bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
