apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:luAYsU5IGJ3D,iv:ZDgIwgN4hlQrJbic7WcRyZ4+eDFzXGWpb20+7pNiT9I=,tag:HdDRkksKEjrwOThFmd9PYw==,type:str]
sops:
    age:
        - recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQlA2RGNaWDA2K3oxdS8v
            RnR4RlgxRlRQK0tEektWSkVXQ2UxQXV4QjNVCmI0QXppc3hXNVo0VmdBZnkxMEtW
            eVh2T1ZrWExPdm5sVW5BcitjMUtTS1EKLS0tIG1ja29yZ3paZUp5ZTVYOFFoamFj
            aWxVYnBiTk9nRGNBa244c3ViTkZPRDQKEgYeaUii9CAv1Qd2uGAjOXHb0StZC7eR
            pHtQFtmWrWQ8iaP6KvsmAn8ybvxATM4Q1CcerBOI6qsJSThvhyDITw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T17:07:11Z"
    mac: ENC[AES256_GCM,data:hVBDl9SxIIgQbCFbBI7D1ql136D8NUcXhqz6kWYqlHR4z7qmWLNBX2TBSmeC9oDWMHiElyfuP66DK5lCTYq6isFU8/y190Y6YhXCGvRrKQMBUyVr3gYl2faa1hC2pf1StRqyCSfNZyJ5ChTNX+6Lx7kWc90OFIVtO1zQZsqZ6Ik=,iv:luqi4DZxJr7pMgNuTx7eAm/fxuySkeLp2YdHp2Wcub0=,tag:XwLn1H4Oro3Rg01c1A7nGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
