apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:NKwN6Cs=,iv:OzdvefKMYC8aIs2X8bOtVVWfc3aw5zkkcauZjnHzhbY=,tag:SSO2jYykgZ/px0O3byGlLw==,type:str]
    admin-password: ENC[AES256_GCM,data:/P2Lb59WyUAB,iv:xbWs159NDg4m9l2vAk5D5pfQgjMgJxEphaEB6RXCGj0=,tag:ZGSauAJcvye0ybw2TIMMgw==,type:str]
sops:
    age:
        - recipient: age1vmka94kas8cez0jm80zyhyx9uahm4ldc5d2tm4yjltmqw2xckfaspauh3c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY2FwYndBcW5LZEhwcVBX
            VFhHMzU0ZlY4M2N1TWFMMW92N3BWaEpjcWswCnU5SFp5UFY2V3AyOGgvV3V5NkJr
            RGJYWmdGd0tibG9hQWNGZmdFTzI2T00KLS0tIG14V3hkdGJINnJvVFhDeEFtUUtq
            Y2t0bFNmMWN1SkhIMlA0eS83RWU1SFEKqI79a9uXAkxTgbQbYdUCgEJyC4wK1wYX
            aMJmBz+eZdJQ5cKM50SG766GooeetuIIPf1lndjGFvdVosqvjWGh4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T21:41:06Z"
    mac: ENC[AES256_GCM,data:rPygh9crjPRs9bPkPfhy+8Sw2hDb6sTXn4GM8nnwFkP5gj+Lo7AxeyiqNBZlgT1ryc8xBsgk1JZHC/K2KSQHSuTdyF2q4DOgCss5nyr7mqsFCVT9nDPkq9sK5LuqjdsdY9EYc8dpikEAO5frAtAq/c91NaorZGrDfBlI4iYjdtA=,iv:G+jOoavD3Gm8fnJ/ZJ2seoL6P+VTNkYeNF0iN6ZrL9A=,tag:j2p/FkSLu4+idEGxuTO2Fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
