apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - loki-repository.yaml
  - release.yaml
  - loki-release.yaml
  - grafana-credentials.enc.yaml
